---
title: "Practice Set Many Variables"
author: "Kevin Green"
date: "7/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Create a histogram of diamond prices.
# Facet the histogram by diamond color
# and use cut to color the histogram bars.

# The plot should look something like this.
# http://i.imgur.com/b5xyrOu.jpg

# Note: In the link, a color palette of type
# 'qual' was used to color the histogram using
# scale_fill_brewer(type = 'qual')

data(diamonds)
library(ggplot2)
names(diamonds)
?facet_wrap

ggplot(aes(x = price, fill = cut), data = diamonds)+
  scale_x_log10()+
  geom_histogram()+
  facet_wrap(~color)+
  scale_fill_brewer(type = 'qual')


```
```{r}
# Create a scatterplot of diamond price vs.
# table and color the points by the cut of
# the diamond.

# The plot should look something like this.
# http://i.imgur.com/rQF9jQr.jpg

# Note: In the link, a color palette of type
# 'qual' was used to color the scatterplot using
# scale_color_brewer(type = 'qual')

ggplot(aes(x=table, y=price, color = cut), data = diamonds)+
  geom_point(position = position_jitter(), alpha = 1/4)+
  scale_fill_brewer(type = 'qual')
```

```{r}
# Create a scatterplot of diamond price vs.
# volume (x * y * z) and color the points by
# the clarity of diamonds. Use scale on the y-axis
# to take the log10 of price. You should also
# omit the top 1% of diamond volumes from the plot.

# Note: Volume is a very rough approximation of
# a diamond's actual volume.

# The plot should look something like this.
# http://i.imgur.com/excUpea.jpg

# Note: In the link, a color palette of type
# 'div' was used to color the scatterplot using
# scale_color_brewer(type = 'div')

diamonds$volume <- with(diamonds, x * y * z)
ggplot(aes(x = volume, y = price, color = clarity), data = subset(diamonds, volume < quantile(volume, 0.99)))+
  geom_point()+
  scale_color_brewer(type = 'div')+
  scale_y_log10()
```
```{r}
# Many interesting variables are derived from two or more others.
# For example, we might wonder how much of a person's network on
# a service like Facebook the user actively initiated. Two users
# with the same degree (or number of friends) might be very
# different if one initiated most of those connections on the
# service, while the other initiated very few. So it could be
# useful to consider this proportion of existing friendships that
# the user initiated. This might be a good predictor of how active
# a user is compared with their peers, or other traits, such as
# personality (i.e., is this person an extrovert?).

# Your task is to create a new variable called 'prop_initiated'
# in the Pseudo-Facebook data set. The variable should contain
# the proportion of friendships that the user initiated.

pf <-read.csv('pseudo_facebook.tsv', sep = '\t')
names(pf)
pf$prop_initiated <- with(pf, friendships_initiated/friend_count)
summary(pf$prop_initiated)

```

```{r}
# Create a line graph of the median proportion of
# friendships initiated ('prop_initiated') vs.
# tenure and color the line segment by
# year_joined.bucket.

# Recall, we created year_joined.bucket in Lesson 5
# by first creating year_joined from the variable tenure.
# Then, we used the cut function on year_joined to create
# four bins or cohorts of users.

# (2004, 2009]
# (2009, 2011]
# (2011, 2012]
# (2012, 2014]

# The plot should look something like this.
# http://i.imgur.com/vNjPtDh.jpg
# OR this
# http://i.imgur.com/IBN1ufQ.jpg


pf$year_joined <- 2014-ceiling(pf$tenure/365)
pf$year_joined.bucket <- cut(pf$year_joined, breaks = c(2004,2009,2011,2012,2014), right = TRUE)

ggplot(pf, aes(x = tenure, y = prop_initiated, color = year_joined.bucket))+
  geom_line(stat = 'summary', fun.y=median, na.rm = TRUE)

```

```{r}
# Smooth the last plot you created of
# of prop_initiated vs tenure colored by
# year_joined.bucket. You can bin together ranges
# of tenure or add a smoother to the plot.

# There won't be a solution image for this exercise.
# You will answer some questions about your plot in
# the next two exercises.

ggplot(pf, aes(x = 25*round(tenure/25), y = prop_initiated, color = year_joined.bucket))+
  geom_line(stat = 'summary', fun.y=median, na.rm = TRUE)

#another alternative
ggplot(pf, aes(x=tenure, y=prop_initiated, color=year_joined.bucket)) +
  geom_smooth(na.rm=TRUE)

```

```{r}
#Largest prop_initiaed group's mean
mean(pf$prop_initiated[pf$year_joined.bucket=='(2012,2014]'], na.rm=TRUE)
```

```{r}
ggplot(diamonds, aes(x=cut, y=price/carat, color=color)) +
  geom_point(position=position_jitter(), alpha=0.33) + 
  facet_wrap(~clarity) +
  scale_color_brewer(type='div')
```



