---
title: "Diamonds and Price Predictions"
author: "Kevin Green"
date: "7/29/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages('ggplot2')
data(diamonds)
library(ggplot2)


# Let's start by examining two variables in the data set.
# The scatterplot is a powerful tool to help you understand
# the relationship between two continuous variables.

# We can quickly see if the relationship is linear or not.
# In this case, we can use a variety of diamond
# characteristics to help us figure out whether
# the price advertised for any given diamond is 
# reasonable or a rip-off.

# Let's consider the price of a diamond and it's carat weight.
# Create a scatterplot of price (y) vs carat weight (x).

# Limit the x-axis and y-axis to omit the top 1% of values.
#Chart with volume
diamonds$volume <- with(diamonds, x*y*z)
ggplot(data = subset(diamonds, volume < quantile(volume, 0.99)), aes(x = carat, y = price))+
  geom_point()
#Right answer
ggplot(diamonds, aes(x = carat, y = price))+
  geom_point(color = 'darkblue', alpha = 0.05)+
  xlim(0, quantile(diamonds$carat,0.99))+
  ylim(0, quantile(diamonds$price, 0.99))
#Another answer with qplot
qplot(data = diamonds, x = carat, y = price,
      xlim = c(0, quantile(diamonds$carat, 0.99)),
      ylim = c(0, quantile(diamonds$price, 0.99)))+
  geom_point(fill = I('#F79420'), color = 'black', shape = 21)
#Another possible chart
ggplot(diamonds, aes(x = carat, y = price))+
  geom_point(fill = I('#ADD8E6'), color = 'black', shape = 21)+
  stat_smooth(method = 'lm')+
  scale_x_continuous(lim = c(0, quantile(diamonds$carat, 0.99)))+
  scale_y_continuous(lim = c(0, quantile(diamonds$price, 0.99)))
  
```

```{r}
install.packages('GGally')
install.packages('scales')
install.packages('memisc')
install.packages('lattice')
install.packages('MASS')
install.packages('car')
install.packages('reshape')
install.packages('plyr')

library(ggplot2)
library(GGally)
library(scales)
library(memisc)

# sample 10,000 diamonds from the data set
set.seed(20022012)
diamond_samp <- diamonds[sample(1:length(diamonds$price),10000),]
ggpairs(diamond_samp,
  lower = list(continuous = wrap("points", shape = I('.'))),
  upper = list(combo = wrap("box", outlier.shape = I('.'))))

```

```{r}
library(gridExtra)

plot1 <- qplot(data = diamonds, x = price, binwidth = 100) + 
  ggtitle('Price')

plot2 <- qplot(data = diamonds, x = price, binwidth = 0.01) +
  ggtitle('Price (log10)')+
  scale_x_log10()

grid.arrange(plot1, plot2, ncol = 2)
```

```{r}
# Scatter Plot Transformations
qplot(carat, price, data = diamonds) +
  scale_y_continuous(trans = log10_trans())+
  ggtitle('Price (log10) by Carat')

# Create a new function to transform the carat variable

cuberoot_trans = function() trans_new('cuberoot',
                                      transform = function(x) x^(1/3),
                                      inverse = function(x) x^3)

# Use the cuberoot_trans function
qplot(aes(carat, price), data = diamonds)+
  geom_point()+
  scale_x_continuous(trans = cuberoot_trans(), limits = c(0.2,3),
                     breaks = c(0.2, 0.5, 1, 2, 3))+
  scale_y_continuous(trans = log10_trans(), limits = c(350,15000),
                     breaks = c(350,1000,5000,10000,15000))
  
  
```
```{r}
head(sort(table(diamonds$carat), decreasing = T))
head(sort(table(diamonds$price), decreasing = T))

# Add a layer to adjust the features of the
# scatterplot. Set the transparency to one half,
# the size to three-fourths, and jitter the points.

# If you need hints, see the Instructor Notes.
# There are three hints so scroll down slowly if
# you don’t want all the hints at once.

# ALTER THE CODE BELOW THIS LINE
# =======================================================================

plot4 <- ggplot(aes(carat, price), data = diamonds) + 
  geom_point(alpha = 1/4) + 
  scale_x_continuous(trans = cuberoot_trans(), limits = c(0.2, 3),
                     breaks = c(0.2, 0.5, 1, 2, 3)) + 
  scale_y_continuous(trans = log10_trans(), limits = c(350, 15000),
                     breaks = c(350, 1000, 5000, 10000, 15000)) +
  ggtitle('Price (log10) by Cube-Root of Carat')

plot5 <- ggplot(aes(carat, price), data = diamonds) + 
  geom_point(alpha = 1/4, position = 'jitter') + 
  scale_x_continuous(trans = cuberoot_trans(), limits = c(0.2, 3),
                     breaks = c(0.2, 0.5, 1, 2, 3)) + 
  scale_y_continuous(trans = log10_trans(), limits = c(350, 15000),
                     breaks = c(350, 1000, 5000, 10000, 15000)) +
  ggtitle('Price (log10) by Cube-Root of Carat')

plot6 <- ggplot(aes(carat, price), data = diamonds) + 
  geom_point(alpha = 1/4, size = 0.75) + 
  scale_x_continuous(trans = cuberoot_trans(), limits = c(0.2, 3),
                     breaks = c(0.2, 0.5, 1, 2, 3)) + 
  scale_y_continuous(trans = log10_trans(), limits = c(350, 15000),
                     breaks = c(350, 1000, 5000, 10000, 15000)) +
  ggtitle('Price (log10) by Cube-Root of Carat')

grid.arrange(plot4, plot5, plot6, ncol = 3)
```



