---
title: "Explore Many Variables"
author: "Kevin Green"
date: "7/23/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pf <- read.csv('pseudo_facebook.tsv', sep = '\t')
data(pf)
library(ggplot2)
ggplot(aes(x = gender, y = age), 
       data = subset(pf, !is.na(gender)))+
  geom_boxplot()+
  stat_summary(fun.y = mean, geom = 'point', shape = 4)

ggplot(aes(x = age, y = friend_count),
       data = subset(pf, !is.na(gender)))+
  geom_line(aes(color = gender), stat = 'summary', fun.y = median)

# Write code to create a new data frame,
# called 'pf.fc_by_age_gender', that contains
# information on each age AND gender group.

# The data frame should contain the following variables:

#    mean_friend_count,
#    median_friend_count,
#    n (the number of users in each age and gender grouping)

# Here is an example of the structure of your data frame. Your
# data values will be different. Note that if you are grouping by
# more than one variable, you will probably need to call the
# ungroup() function. 

#   age gender mean_friend_count median_friend_count    n
# 1  13 female          247.2953                 150  207
# 2  13   male          184.2342                  61  265
# 3  14 female          329.1938                 245  834
# 4  14   male          157.1204                  88 1201

pf.fc_by_age_gender <- pf %>%
  filter(!is.na(gender)) %>%
  group_by(age, gender) %>%
  summarise(mean_friend_count=mean(friend_count),
            median_friend_count=median(friend_count),
            n=n())

# Create a line graph showing the
# median friend count over the ages
# for each gender. Be sure to use
# the data frame you just created,
# pf.fc_by_age_gender.

ggplot(aes(x = age, y = median_friend_count),
       data = pf.fc_by_age_gender)+
  geom_line(aes(color = gender), stat = 'summary', fun.y = median)

install.packages('reshape2')
library('reshape2')
pf.fc_by_age_gender.wide <- dcast(pf.fc_by_age_gender,
                                  age ~ gender,
                                  value.var = 'median_friend_count')

# Plot the ratio of the female to male median
# friend counts using the data frame
# pf.fc_by_age_gender.wide.

# Think about what geom you should use.
# Add a horizontal line to the plot with
# a y intercept of 1, which will be the
# base line. Look up the documentation
# for geom_hline to do that. Use the parameter
# linetype in geom_hline to make the
# line dashed.

# The linetype parameter can take the values 0-6:
# 0 = blank, 1 = solid, 2 = dashed
# 3 = dotted, 4 = dotdash, 5 = longdash
# 6 = twodash

ggplot(pf.fc_by_age_gender.wide, aes(age, y=female/male)) + geom_line() +
  geom_hline(yintercept=1, alpha=0.3, linetype=2) +
  xlab('Age') +
  ylab('Median Female Friend Count / Median Male Friend Count')

pf$year_joined <- floor(2014- pf$tenure/365)

summary(pf$year_joined)
table(pf$year_joined)

pf$year_joined.bucket <- cut(pf$year_joined,
                          c(2004,2009, 2011, 2012, 2014))
pf$year_joined.bucket
head(pf$year_joined.bucket)

table(pf$year_joined.bucket, useNA = 'ifany')

ggplot(aes(x = age, y = friend_count), data = subset(pf, !is.na(year_joined.bucket)))+
  geom_line(aes(color=year_joined.bucket), stat='summary', fun.y=median)

# Write code to do the following:

# (1) Add another geom_line to code below
# to plot the grand mean of the friend count vs age.

# (2) Exclude any users whose year_joined.bucket is NA.

# (3) Use a different line type for the grand mean.

# As a reminder, the parameter linetype can take the values 0-6:

# 0 = blank, 1 = solid, 2 = dashed
# 3 = dotted, 4 = dotdash, 5 = longdash
# 6 = twodash

# ==================================================================
ggplot(aes(x = age, y = friend_count), data = subset(pf, !is.na(year_joined.bucket))) +
  geom_line(aes(color=year_joined.bucket), stat='summary', fun.y=mean) +
  geom_line(stat='summary', fun.y=mean, linetype=2)


summary( with(subset(pf, tenure>0), friend_count/tenure) )

# Create a line graph of mean of friendships_initiated per day (of tenure)
# vs. tenure colored by year_joined.bucket.

# You need to make use of the variables tenure,
# friendships_initiated, and year_joined.bucket.

# You also need to subset the data to only consider user with at least
# one day of tenure.

# ========================================================================
ggplot(subset(pf, tenure>0), aes(x=tenure, y=friendships_initiated/tenure, color=year_joined.bucket)) + 
  geom_line(stat='summary', fun.y=mean)

library(gridExtra)
## 
## Attaching package: 'gridExtra'
## The following object is masked from 'package:dplyr':
## 
##     combine
p1 <- ggplot(aes(x = tenure, y = friendships_initiated / tenure),
       data = subset(pf, tenure >= 1)) +
  geom_line(aes(color = year_joined.bucket),
            stat = 'summary',
            fun.y = mean)

p2 <- ggplot(aes(x = 7 * round(tenure / 7), y = friendships_initiated / tenure),
       data = subset(pf, tenure > 0)) +
  geom_line(aes(color = year_joined.bucket),
            stat = "summary",
            fun.y = mean)

p3 <- ggplot(aes(x = 30 * round(tenure / 30), y = friendships_initiated / tenure),
       data = subset(pf, tenure > 0)) +
  geom_line(aes(color = year_joined.bucket),
            stat = "summary",
            fun.y = mean)

p4 <- ggplot(aes(x = 90 * round(tenure / 90), y = friendships_initiated / tenure),
       data = subset(pf, tenure > 0)) +
  geom_line(aes(color = year_joined.bucket),
            stat = "summary",
            fun.y = mean)

grid.arrange(p1,p2,p3,p4, ncol=1)

# Instead of geom_line(), use geom_smooth() to add a smoother to the plot.
# You can use the defaults for geom_smooth() but do color the line
# by year_joined.bucket

# ALTER THE CODE BELOW THIS LINE
# ==============================================================================

ggplot(aes(x = 7 * round(tenure / 7), y = friendships_initiated / tenure),
       data = subset(pf, tenure > 0)) +
  geom_smooth(aes(color = year_joined.bucket))

yo <- read.csv('yogurt.csv')
str(yo)

yo$id <- factor(yo$id)
str(yo)

library(ggplot2)
ggplot(aes(x = price), data = yo)+
  geom_histogram()


# Create a new variable called all.purchases,
# which gives the total counts of yogurt for
# each observation or household.

# One way to do this is using the transform
# function. You can look up the function transform
# and run the examples of code at the bottom of the
# documentation to figure out what it does.

# The transform function produces a data frame
# so if you use it then save the result to 'yo'!

# OR you can figure out another way to create the
# variable.
# ========================================================

names(yo)
table(yo$blueberry)
head(yo)
yo <- transform(yo, all.purchases=strawberry+blueberry+pina.colada+plain+mixed.berry)

# alternate method
yo$all.purchases <- with(yo, strawberry+blueberry+pina.colada+plain+mixed.berry)

# Create a scatterplot of price vs time.

# This will be an example of a time series plot.

# Resolve overplotting issues by using
# techniques you learned in Lesson 4.

# What are some things that you notice?

ggplot(aes(x=time, y= price), data = yo) +
  geom_jitter(alpha = 1/4, shape = 21, fill = I('#F79420'))


## Looking at Sample Households
set.seed(4230) 
sample.ids <- sample(levels(yo$id), 16)

ggplot (aes(x = time, y = price), 
        data = subset(yo, id %in% sample.ids)) + 
  facet_wrap(~ id) +
  geom_line() +
  geom_point(aes(size = all.purchases), pch = 1)

?set.seed

install.packages('GGally')
library(GGally)
theme_set(theme_minimal(20))

# set the seed for reproducible results
pf <- read.csv('pseudo_facebook.tsv', sep = '\t')
set.seed(1836)
pf_subset <- pf[, c(2:15)]
#pf_subset <- subset(pf, select = -c(userid, year_joined, year_joined_bucket))
names(pf_subset)
ggpairs(pf_subset[sample.int(nrow(pf_subset), 1000),])

```


